export {default as user_pic} from './Ellipse 5.png'
export {default as logo_pic} from './Rectangle 28.png'
export {default as dash_pic} from './Rectangle 25.png'
export {default as emp_pic} from './Rectangle 26.png'
export {default as att_pic} from './Rectangle 142.png'
export {default as attens_pic} from './Rectangle 143.png'
export {default as shift_pic} from './Rectangle 144.png'
export {default as leave_pic} from './Rectangle 145.png'
export {default as  reim_pic} from './Rectangle 146.png'
export {default as resign_pic} from './Rectangle 147.png'
export {default as salary_pic} from './Rectangle 148.png'
export {default as pay_pic} from './Rectangle 149.png'
export {default as payroll_pic} from './Rectangle 150.png'
export {default as holiday_pic } from './Rectangle 151.png'
export {default as reports_pic} from './Rectangle 152.png'
export {default as announcement_pic} from './Rectangle 153.png'
export {default as admin_pic} from './Rectangle 154.png'
export {default as Bulk_Upload} from './Bulkupload-logo-removebg-preview.png'
export {default as Tableheading_bg} from './images.png'
export {default as login_bg2} from "./6114100.jpg"